### ISSUE TITLE
Add support to introspect EntityExceptions data

### ISSUE THREAD

**Issue by ramsai1729** [Terracotta-OSS/terracotta-apis#127]
- Add support to introspect EntityExceptions data
- Add a constructor to set cause for EntityAlreadyExistsException, EntityNotFoundException, EntityNotProvidedException, EntityVersionMismatchException and PermanentEntityException 

This support is needed for Terracotta-OSS/terracotta-core#253 where we need re-create the corresponding exception on client side

**Comment by jd0-sag** [comment]
This looks good.  I can merge it once I get some sense of whether or not we wanted to address any other API changes in the next release and how to coordinate that.
