### ISSUE TITLE
Document concurrency levels for Active and Passiver ServerEntity APIs

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/terracotta-apis#144]
There have been recent questions as to what exactly are the concurrency guarantees for methods on `ActiveServerEntity` and `PassiveServerEntity`.

Example questions:
* Are `connected` and `disconnected` calls serialised or concurrent?
* Are `connected` or `disconnected` calls concurrent or serialised with `invoke`?

I believe this is the kind of information that the Javadoc of the respective types should provide to help entity implementors understand under which guarantees they operate.

**Comment by jd0-sag** [comment]
The short answer is that any non-`invoke` (or sync-related) calls are run on `MANAGEMENT_KEY`, meaning that they are serialized.

This is mentioned in the `ConcurrencyStrategy` JavaDoc but it should be made more explicit in the other classes, as well (especially considering that sync is the other case which isn't serialized but that isn't correctly spelled out).
