### ISSUE TITLE
Being able to configure a @Builtin Service

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#152]
Currently, a @Builtin service cannot be configured through XML. 

This request is to be able to optionally configure a @Builtin service if an XML config is present. 

The main use case I see is if we need, one day, to make our service that was builtin optionally configurable because some options are added.

So to keep backward compat', the service will need to support both @Builtin AND if provided, be configured by the XML config.

**Comment by mathieucarbou** [comment]
notify: @chrisdennis @ChrisGreenaway @myronkscott @jd0-sag @ljacomet

**Comment by ljacomet** [comment]
Might be something we may need indeed. But that's also something that can be added while being completely compatible IMO. So I do not see the point of adding it now unless really needed.

Makes sense?

**Comment by mathieucarbou** [comment]
Yes, for M&M, but I know @ChrisGreenaway might need it also.

**Comment by myronkscott** [comment]
This has been implemented.  If a configuration is in tc-config, that will be used instead of the builtin.
