### ISSUE TITLE
Expose server name (potentially other data, in the future) to ServiceProvider.initialize

### ISSUE THREAD

**Issue by ramsai1729** [Terracotta-OSS/terracotta-apis#157]
Configured ServiceProviders currently only have the information provided directly from the configuration.

Historically, the server name would be plumbed down into parts of the server for things like data and logging directories so that each server could further namespace their output, per-server.  This makes the organization more meaningful but also protects against subtle collisions in stripe configuration where multiple servers may end up seeing the same path (either on the same machine or a shared volume).

We should formalize this information for all ServiceProviders by wrapping it in an object (in case we have other future requirements) and providing it to ServiceProviders in their `initialize()` method, just like their existing configuration.

**Comment by mathieucarbou** [comment]
Hi @ramsai1729 @jd0-sag : is this API will be available for M&M, as a voltron service or else ? 

Because it might be in our interest to view the platform config from the management apps. 

Thanks!

@anthonydahanne : FYI.

**Comment by jd0-sag** [comment]
This is just a way to pass the server name into `ServerProvider` instances, when they are initialized, to solve problems such as how to namespace storage, etc, in case multiple servers from the same stripe are configured on the same machine with the same paths.

In fact, I will update the name and description.
