### ISSUE TITLE
Server Entity init() method

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#165]
We have a little issue in management regarding when we can expose management metadata (server entity description, states, stats, etc).

When the server entity is creating (`createActiveEntity` or `createPassiveEntity` methods), Voltron did not yet inform us (in the monitoring service) that the entity is created. Which is completely normal.

Thus, it has the impact that we cannot expose any management things to the TMC at this step. The only choice we have is to wait for a first interaction to this server entity (so when a client connects, or when a passive entity received a message). So this is at this moment where the TMC will be able to know about a server entity settings, stats, etc.

This is bad, because TMC will be unable to display any information or store / pool usage of an entity that has not yet been used, but has some allocated stuff (I think about a passive that takes over for example, but clients do not reconnect, or an entity that was used but not anymore after a server restart), or also an entity that uses a common service that allocates stores, then we won't be able to access the store information.

So more generally, this is like we would need a sort of `init()` method __that is called by the platform after the server entity (active and passive) is created and is ready to be used, after the platform notified the monitoring service about the entity creation, but BEFORE any interactions start on it.__

**Comment by jd0-sag** [comment]
I don't understand what the platform would do, in this case, which wouldn't be better solved by just calling from the entity which wants to provide the information.

If an entity has some data to provide when it is first initialized, it can make that call, itself.

I don't think I understand what the problem is, here.

**Comment by mathieucarbou** [comment]
@ljacomet : would it be fine if I trigger an init() call after the entity is created  in ehcache to initialize correctly the management things ? 
If not, which method currently existing I can use that is called after entity creation but once ?
Thanks!

**Comment by myronkscott** [comment]
I think `ServerEntity.createNew()` is what you are looking for, correct?

**Comment by mathieucarbou** [comment]
Yes! thanks you!
