### ISSUE TITLE
ExecutionStrategy.Location needs to be in common apis

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/terracotta-apis#166]
Currently, it is found in the server API which prevents messages that exist on both client and server to use it.
And this is desired if you want messages that can be of a given type but still have different execution strategy.

**Comment by myronkscott** [comment]
ExecutionStrategy is a server side concept.  ExecutionStrategy.Location should not be part of the message, it should be derived from the message at the server.  This could be as simple as reading a woolen flag in the message.
