### ISSUE TITLE
Discussions about an eventual TimeSource service

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#167]
At several places we need to get a timestamp `System.currentTimeMillis()` in management on server-side (i.e. when polling ehcache stats, when creating management messages, etc.)

Currently there is no uniform way to get the current time, i.e. through a voltron `TimeSource` service, like it is done in Ehcache.

Is it something that we would want to have ? Or we continue calling `System.currentTimeMillis()` on server entities ?

**Comment by jd0-sag** [comment]
I suppose it depends on why things like EhCache create their own time source.  If that applies here, we should look into it.  Otherwise, `System.currentTimeMillis()` is as good an answer as any.

**Comment by myronkscott** [comment]
I could see M&M wanting some type of synchronized time source.  That can be added externally as any other server I would think.  Would there be some reason to make it part of standard-cluster-services?

**Comment by mathieucarbou** [comment]
It is not to be used as a synchronization mechanism, is is much more intended to be used within the same server to get a timestamp, much more for ordering and computing diffs. 

But the main concern is much more; do we want a common TimeSource service where time would be taken from a common and same way, or everybody ca ndo what he wants and call, or not, `System.currentTimeMillis()` ?

**Comment by mathieucarbou** [comment]
Adding reference to ehcache/ehcache3#1573

**Comment by jd0-sag** [comment]
The question which must first be answered is "why is `System.currentTimeMillis()` insufficient?"

Without knowing what else we would need, we can't really describe what this would be.

**Comment by mathieucarbou** [comment]
For M&M, it is sufficient at runtime, but not for testing, since we have no control over values. Yes we could have a service returning System.currentTimeMs() but it seems to me that everyone would be interested in such service.

So having a `TimeSourceService` in tc-platform seems reasonable for me.

Probably the Ehcache team also have some inputs since on client-side they have a TimeSource object, that everyone should use when dealing with time / duration. So they could answer your question better than I I think.

**Comment by myronkscott** [comment]
Closing this issue for now.  Value proposition in not met at this time.
