### ISSUE TITLE
Have entity informed of the closing of the reconnect window

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/terracotta-apis#183]
Currently in Ehcache, with state split between client and server, we end up having weird behaviours due to the entity never knowing when the reconnect window closes.
See ehcache/ehcache3#1626.

So could we discuss the pros and cons of having such an event exposed to entities? Either as part of the entity API or through a specific interface that entities could implement if that event interests their instances.

**Comment by myronkscott** [comment]
fixed in https://github.com/Terracotta-OSS/terracotta-apis/blob/master/entity-server-api/src/main/java/org/terracotta/entity/ActiveServerEntity.java#L121
