### ISSUE TITLE
Document multiplicity of EntityClientEndpoint

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-apis#198]
Calls to EntityClientService.create() are passed an EntityClientEndpoint. The javadoc should make it clear that this is a different instance for each entity.

This is distinction is important because, if the same EntityClientEndpoint were passed for the creation of two separate entities, then when calling setDelegate on the endpoint, the entities must co-operate so as not to overwrite each others delegate.

**Comment by jd0-sag** [comment]
Sure - I can add more clarifications around this JavaDoc.
