### ISSUE TITLE
Allow extra "user data" argument through EntityRef.fetchEntity to EntityClientService.create

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/terracotta-apis#202]
There is currently no way to pass additional data through to the constructor of a client-side entity (endpoint wrapper).  Allowing this would make it possible to write smaller and more restrictive code (via final variables and other immutability concepts) within the client-side entity.

This would require changing some parts of the API:

At the top-level, this would require changing `EntityRef.fetchEntity()` into `EntityRef.fetchEntity(Object)`.

At the level of the user-provided `EntityClientService`, it would change the interface from `EntityClientService.create(EntityClientEndpoint)` to `EntityClientService.create(EntityClientEndpoint, Object)`.

Note that we should be able to make these into real generics instead of just `Object`.

**Comment by jd0-sag** [comment]
This has been deferred until after the current release.

**Comment by ChrisGreenaway** [comment]
What's the status of this change? Now that we are past the release (nearly?) Has the work already been done on a branch and it waiting to be integrated, or perhaps it isn't started yet, or...?

**Comment by jd0-sag** [comment]
I have a bunch of PRs, locally, but they are still waiting until we are completely done with X.2.x releases.
