### ISSUE TITLE
Provide a secondary InvocationBuilder

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-apis#207]
InvocationBuilder options provide action based semantics for the programmer where various actions are opted into and out of.  The goal here is to provide a second interface that is results based, where the programmer will opt into result behaviors and the underlying implementation will choose the correct options.  For example, if a user selects "fire and forget" semantics, the implementation will select the correct acknowledgements and return an immediate future.

**Comment by jd0-sag** [comment]
Is this part of the core API or some downstream library, like terracotta-platform?

**Comment by myronkscott** [comment]
Nothing other than packaging requires that this api live here.

**Comment by myronkscott** [comment]
This is not in the scope of current API level work
