### ISSUE TITLE
Provide the ability to return multiple Service instances from ServiceRegistry

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-apis#217]
There may be instances where an entity would like to use multiple services implementing the same interface.  Provide the ability to return a collection of services based on a configuration

**Comment by mathieucarbou** [comment]
@myronkscott : do you have an ETA for this one ? Thanks!

CC: @ankitamaurya @anthonydahanne @ljacomet 

Link: https://github.com/Terracotta-OSS/terracotta-platform/issues/310
