### ISSUE TITLE
EntityClientEndpoint.didCloseUnexpectedly should be removed

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/terracotta-apis#236]
The method `org.terracotta.entity.EntityClientEndpoint#didCloseUnexpectedly` seems like an internal one that no user of the client Entity API should ever invoke.

If that is confirmed, it should disappear from this interface and only exist as an internal one (implementation or interface) reserved for platform usage.

**Comment by myronkscott** [comment]
This looks correct.  Will fix.

**Comment by ChrisGreenaway** [comment]
Presumably getExtendedReconnectData should be removed too.

**Comment by myronkscott** [comment]
yes.  i think these methods helped unify the vision for passthrough and core.  they are no longer needed as they are implementation details
