### ISSUE TITLE
Support arrays in StateDumpCollector

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#242]
I often need to dump states for arrays and there is no `StateDumpCollector.appendState('key', value)` method so I have to workaround that with something ugly by using a counter:

```
    Collection<ClientDescriptor> clients = getClients();
    StateDumpCollector clientsDumper = stateDumpCollector.subStateDumpCollector("clients");
    int i = 0;
    for (ClientDescriptor client : clients) {
      clientsDumper.addState(String.valueOf(i++), client.toString());
    }
```

**Comment by ChrisGreenaway** [comment]
This would definitely be useful and was something both Chris D and I pointed out would be useful on the state dump API before it was first merged.

**Comment by myronkscott** [comment]
If you want rich reporting techniques like this, I suggest you use the JSON string key and just report your information that way.

**Comment by ChrisGreenaway** [comment]
Who wants to be generating JSON? We could get rid of the JSON completely as far as I care.

**Comment by mathieucarbou** [comment]
I think the current json support of flawed to be correctly used (see #240). I would rather have no json support at all and array support, then platform format objects and arrays like it wants, or a real json support. But not incomplete pieces of both ;-)

**Comment by mathieucarbou** [comment]
code discussed:

```
  @Override
  public final void addStateTo(StateDumpCollector stateDumpCollector) {
    stateDumpCollector.addState("instance", this.toString());
    // clients, by default for all active entities
    Collection<ClientDescriptor> clients = getClients();
    stateDumpCollector.addState("clientCount", String.valueOf(clients.size()));
    
    {
      StateDumpCollector clientsDumper = stateDumpCollector.subStateDumpCollector("clients");
      int i = 0;
      for (ClientDescriptor client : clients) {
        clientsDumper.addState(String.valueOf(i++), String.valueOf(client));
      }
    }

    // better alternative
    {

      for (ClientDescriptor client : clients) {
        stateDumpCollector.appendState("clients", String.valueOf(client));
      }
    }

    // custom
    dumpState(stateDumpCollector);
  }
```

far better alternative (to me)

```
  // voltorn code:
  // JsonObjectBuilder dump = Json.createObjectBuilder();
  // XYZ.addStateTo(JsonObjectBuilder dump) {
  // dump.build()
  @Override
  public final void addStateTo(javax.json.JsonObjectBuilder dump) {
    dump
        .add("instance", this.toString())
        .add("clients", getClients().stream()
            .reduce(Json.createArrayBuilder(), (json, client) -> json.add(String.valueOf(client)), JsonArrayBuilder::add));

    // custom
    dumpState(dump);
  }
```

**Comment by myronkscott** [comment]
How about then moving this out of the API and the platform will include a standard library in implementation that provides this type of functionality.  Those that want this can pull it in from there.

**Comment by mathieucarbou** [comment]
@myronkscott : a little like the monitoring support jar that we depend for the monitoring service, but that is provided by platform ?

```
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>monitoring-support</artifactId>
      <scope>provided</scope>
    </dependency>
```

**Comment by ChrisGreenaway** [comment]
I don't understand why we are so desperate to have JSON.

If we do decide that's what's wanted then we can just get rid of the rest of the state API, can't we? Then calling code can just do JSON.

Not sure why there are two systems.

**Comment by myronkscott** [comment]
JSON is human readable so it can be both directly reported as part of the state collection and can also be parseable in the event that platform wants to do reformatting or reporting in a different format.  For now we will just be reporting through directly.  Refer to  Terracotta-OSS/terracotta-platform#346 for an alternate method of reporting.

**Comment by ChrisGreenaway** [comment]
Mathieu - are you happy to close this issue given that we have a relatively standard way of doing this from the calling side instead?

**Comment by mathieucarbou** [comment]
I still think this is not ideal from a user point of view but it would work.

@ljacomet : do you have any concern if all entities / services depends on the new state-format module from https://github.com/Terracotta-OSS/terracotta-platform/pull/346 ? Especially for the packaging ?

@myronkscott @ChrisGreenaway : would it be a "provided" scope dependency, and it means that state-format will ALWAYS be in the kit  ?

**Comment by ChrisGreenaway** [comment]
@mathieucarbou I thought you were doing it without using the JSON API - just using numbered sub collectors.

**Comment by mathieucarbou** [comment]
yes @ChrisGreenaway , because I do not have any other choice at the moment
