### ISSUE TITLE
ActiveServerEntity and clients that do not reconnect

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-apis#244]
Sequence that causes problem:
1. Per client state replicated to passive.
2. Active dies.
3. Passive becomes new active.
4. Some clients reconnect to the new active, but not all.
5. Resources for the clients that did not reconnect should be released.

Perhaps, at the end of the reconnect window, disconnect() is already called for each client that does not reconnect. If so this should be made clear in the javadoc. If not then this might be an acceptable solution.

Alternatively a method such as noMoreReconnections() could be added to ActiveServerEntity.

**Comment by myronkscott** [comment]
Fixed with API changes in PR #249.
