### ISSUE TITLE
InvocationBuilder.invoke and timeouts

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-apis#248]
On InvokeFuture you can get(timeout), but InvocationBuilder.invoke() does not have such a timeout, even though it too may block pending acks.

InvocationBuilder.invoke() should probably also throw InterruptedException.

**Comment by myronkscott** [comment]
This sounds right but it means that the message will still be invoked on the server and the client will be in some unknown state.  Would probably require some very nuanced interrupt handling by the entity and I'm not sure we can reliably coordinate between platform and entity in that situation.

**Comment by myronkscott** [comment]
Looking at this more, I think the right usage to achieve timeout behavior, is to not use any acks on invoke and rely solely on InvokeFuture.getWithTimeout() for the behavior you desire.

**Comment by myronkscott** [comment]
Please close if you agree

**Comment by ChrisGreenaway** [comment]
Sounds fine to me.
