### ISSUE TITLE
Unable to self message a ClientDescriptor

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-apis#255]
Removing the serialization of ClientDescriptor means that the active can't send itself a message about a particular client.

**Comment by myronkscott** [comment]
The active entity should keep some sort of map of local identifier to clientdescriptor if it wants to messageSelf with reference to a particular client.  The clientdescriptor is opaque and intended to be local the the active entity.

**Comment by ChrisGreenaway** [comment]
Yes, a map like that is what I ended up doing. Just wanted to check, with all the change around ClientDescriptor and ClientSourceId, that this had shaken out the way you wanted it.
