### ISSUE TITLE
Establish independant serialization/deserialization contract for ClientSourceId

### ISSUE THREAD

**Issue by albinsuresh** [Terracotta-OSS/terracotta-apis#262]
The current impl provides a serialization mechanism via the `ClientSourceId.toLong` method. But the deserialization requires an `InvokeContext`. This prevents deserialization from not within the context of an invoke. So that deserialization API should be decoupled from the `InvokeContext`.

**Comment by myronkscott** [comment]
Please describe a scenario where you would need to deserialize outside an InvokeContext.  Any message will arrive on the target server with an invoke context and should be deserialized at that time.

**Comment by myronkscott** [comment]
will not do.  Please reopen if you still find this necessary
