### ISSUE TITLE
`RuntimeEntityException` subclasses should require entity name and type info.

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-apis#263]
In order to avoid accidental omission of entity name and type information from exception messages we shouldn't have constructors for `RuntimeEntityException` subclasses that don't take entity and type information.

**Comment by myronkscott** [comment]
Addressed by Terracotta-OSS/terracotta-core#726.  All exceptions have the type and name information added to them when thrown locally on the client

**Comment by chrisdennis** [comment]
The improvements are good... but the exception that led me to this was `ConnectionClosedException`.  Re-opening to see if that one can be fixed.

**Comment by myronkscott** [comment]
Unfortunately, in order to fix that one, the exception is re-wrrapped into LocalConnectionClosedException.  Are you sniffing the exception stack or just checking the type and name of the top level exception?

**Comment by chrisdennis** [comment]
My bad... should have looked closer at the changeset.
