### ISSUE TITLE
EntityRef could benefit from a non-blocking way of performing an entity destroy

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-apis#27]
Right now there is no way to attempt to destroy an entity and detect failure due to the holding of existing entity references.  This would seem like a useful addition to the api.

**Comment by jd0-sag** [comment]
This will be added in addition to the existing EntityRef API, not removing the existing destroy() call:

    boolean tryDestroy() throws EntityNotProvidedException, EntityNotFoundException;

Will attempt to acquire the exclusive lock on the entity and destroy the entity instance.  Returns true on success, false if the lock could not be acquired, throws EntityNotProvidedException if there is no provider for the entity type, and EntityNotFoundException if the entity didn't exist.

**Comment by chrisdennis** [comment]
First glance says that looks fine to me.  Are we leaving the original method because we think it has value or are we just going to deprecate it?

**Comment by jd0-sag** [comment]
Original method will remain because it is easy to leave in and you otherwise need to implement all delete operations as loops.

It won't be deprecated, either, as they both seem to address different usage patterns, both being valid.
