### ISSUE TITLE
add reconnectComplete() callback to ActiveServerEntity

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-apis#272]
ActiveServerEntities are responsible to handle reconnect data from clients once they are promoted to active from passive.  This series of callbacks happen in a very ordered fashion where reconnects from existing clients are processed, then resent transactions from the clients are processed, then new requests are processed.  Add an extra step in the callback process where ActiveServerEntities are notified that they will no longer receive any handleReconnects with the callback method `ActiveServerEntity.reconnectComplete()` which will occur after all reconnects have been processed but before and ressent transactions will be delivered.

**Comment by myronkscott** [comment]
@ljacomet is this sufficient for current needs?

**Comment by myronkscott** [comment]
@ljacomet In thinking about this some more, your needs might be better served but either using deferred retirement so that the message is resent from the client that is expecting the final completion message.  Another alternative would be to use `IEntityMessenger.messageSelf()` upon `ActiveServerEntity.loadExisting()` callback.  This would work since delivery of this message is guaranteed to occur after all reconnect messages have been delivered.

This is better since doing this at the platform level would force messaging to all entities, a vast majority that will not need the signaling.

**Comment by ChrisGreenaway** [comment]
For an example of where we needed to be informed about reconnection completing, see the LeaseReconnectFinished class in terracotta-platform. We jumped through a lot of hoops to make the reconnect semantics work - including those "connection sequence numbers".

**Comment by myronkscott** [comment]
@ChrisGreenaway I think you could have accomplished your desired result by collecting all ClientDescriptors under `handleReconnect()` and sending a single `LeaseReconnectFinished` message under the `loadExisting()` callback.

**Comment by myronkscott** [comment]
addressed with ReconnectHandler

https://github.com/Terracotta-OSS/terracotta-apis/blob/master/entity-server-api/src/main/java/org/terracotta/entity/ActiveServerEntity.java#L121
