### ISSUE TITLE
ConnectionFactory.connect should have explicit alternate

### ISSUE THREAD

**Issue by cschanck** [Terracotta-OSS/terracotta-apis#284]
By this I mean we should have an entry point that requires no parsing. 

Connectionfactory.connect(List<InetSocketAddress> hosts, Properties props);

for example. Where we give it a list of host/port pairs explicitly, no parsing at all. There is no reason for the internals to be aware of the textual representation of the list of host/port pairs. 

InetSocketAddress might be overkill for this, but it serves as an example. 

All other connect() methods should delegate to this new one.

**Comment by saurabhagas** [comment]
This also enables us to pass in multiple IPv6 addresses, which is not possible with the current API.

Thus, I propose the following two APIs:
`ConnectionFactory.connect(List hosts, Properties props)`
`ConnectionFactory.connect(String scheme, List hosts, Properties props)`

The first will use the default `terracotta` scheme, and the second allows the user to pass in other schemes like `diagnostic`.

**Comment by saurabhagas** [comment]
Code changes merged. Closing the issue.
