### ISSUE TITLE
New API for entity instance to determine the server name

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-apis#291]
In my entity, I need the server name (e.g. the result of TCServerMain.server.getL2Identifier()) in order to provide feedback about where the code is running. This is currently not available.

**Comment by myronkscott** [comment]
Can you access this through a service being used by your entity?

https://github.com/Terracotta-OSS/terracotta-apis/blob/master/entity-server-api/src/main/java/org/terracotta/entity/PlatformConfiguration.java#L33

**Comment by ChrisGreenaway** [comment]
That seems to do the job. Thanks.
