### ISSUE TITLE
Ability to attempt to destroy an entity from within itself.

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-apis#302]
In order to clean-up unused entities once all clients have left (when they contain no interesting state), I'd like to be able to trigger a destroy attempt (failure is okay) from within the `disconnected(ClientDescriptor)` method by some mechanism.

**Comment by mathieucarbou** [comment]
@anthonydahanne @chrisdennis  : 
This is something that would also allow M&M to "clean" unused entities too (i.e. NMS Entity) when TMS crashes or leaves.
This would allow to automatically destroy the NSM entities (active & passive) and consequently unschedule the task on voltron service that is collecting the statistics. 

Currently, this scheduled task keeps running even if no client are there to receive the collected statistics.

**Comment by myronkscott** [comment]
I propose an annotation TemporaryEntity, similar to PermanentEntity, that will delete an entity that has been fetched then released with no other references.  I will also add a method to IEntityMessenger deleteSelf() that will attempt delete if all references are gone.  This will allow us to make this change without breaking any existing API
