### ISSUE TITLE
New constants for server states in PlatformMonitoringConstants

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#37]
Currently, there are:

```
STOPPED,
ACTIVE,
PASSIVE,
```

(https://github.com/Terracotta-OSS/terracotta-apis/tree/master/monitoring-support/src/main/java/org/terracotta/monitoring)

we also had before:

```
PASSIVE_UNINITIALIZED,
START_STATE,
RECOVERING,
```

@anthonydahanne, Gary: 2 questions:

1. do we still need the 3 others ?
2. do we rename them to SYNCING, STARTING, RECOVERING ?

**Comment by jd0-sag** [comment]
I would assume that the other states of of value but we need to determine whether to just pass them through, verbatim (in which case you can't really rely on their meanings since they are just internal names and could change if the state machine is altered), or do we want to define a solid set of meaningful names and we will internally map our states to those (in which case you can make high-level decisions based on the values).

**Comment by anthonydahanne** [comment]
those first 3 (STOPPED, ACTIVE, PASSIVE) represent "stable" states, and the others (PASSIVE_UNINITIALIZED, START_STATE, RECOVERING) "transition" states. 
I would second Jeff, saying we should keep such transitions states - we'll see if we rename them later

**Comment by mathieucarbou** [comment]
I would prefer we see know if we give them better name. I mean... if START_STATE means "starting", then is should be called STARTING, not START_STATE. Jeff already renamed existing states: ACTIVE_COORDONATOR, PASSIVE_STANDBY, etc to more readable names. So I suggest we do the same for transition states if we need them.

So I suggested: SYNCING, STARTING, RECOVERING. Does it work for you @anthonydahanne  and Gary ?

**Comment by anthonydahanne** [comment]
LGTM

**Comment by myronkscott** [comment]
At first glance, some of these states seem superfluous. Stopping and starting for example are probably not observable, particularly from the network. It probably makes sense to concentrate on network readiness (or lack thereof) states

**Comment by mathieucarbou** [comment]
Right... So perhaps we can just keep at the moment the 3 states @jd0-sag exposed, and see whether we need or not some other states after. As I understood we probably won't have the same things as before.

@jd0-sag, @myronkscott : do we keep this issue opened then, for future reference ? Or we close it ?

**Comment by jd0-sag** [comment]
I will leave this open, for now, to see what happens once you actually meet this integration point since we have some amount of relevant conversation here, already.

I will mark it as low priority, though.

**Comment by jd0-sag** [comment]
Assigning to @myronkscott as you have done work which probably encompasses the meaning of this issue.

**Comment by myronkscott** [comment]
Adding SYNCHRONIZING to the states that a server can be in.  This is when a server is going from UNINITIALIZED to PASSIVE.  Currently the possible transitions for a server are:

UNINITIALIZED->SYNCHRONIZING->PASSIVE->ACTIVE
UNINITIALIZED->ACTIVE

**Comment by mathieucarbou** [comment]
@myronkscott : is the STOPPED state removed ? If not, is it a state that M&M could observe ?

In the case for example when a passive server crashed, and the monitoring tree containing all the servers would then be updated to mark the passive STOPPED for example ? Could it be possible ?

Thanks!

**Comment by jd0-sag** [comment]
If a passive server crashes, I would assume that we just remove it from the tree, as opposed to putting it into some different state (after all, it is NOT recoverable).

I don't know if STOPPED can be meaningfully observed by I will defer to Myron on that.

**Comment by myronkscott** [comment]
STOPPED is not really something observable.  We cannot put it in the tree as we do not have any node-id associated with it.  I can understand MandM wanting to display missing servers.  Can you do this by comparing config with nodes in the tree?

**Comment by mathieucarbou** [comment]
Yes we can!  I asked because STOPPED is still in `PlatformMonitoringConstants `.
