### ISSUE TITLE
Possible API changes

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-apis#39]
ConcurrencyStrategy.getKeysForSynchronization() should be renamed to ConcurrencyStrategy.keys() or something more general and should be an iterator.  Alternately, ConcurrencyStrategy should be made iterable().  -- The justification for this is that implementations of this class will likely involve some mathematical function.  It would be nice if the range of keys could be generated rather than provided at once as a set.

**Comment by myronkscott** [comment]
looks like AbstractSet can be subclassed so that only iterator and size need to be implemented.  Maybe API is not really an enhancement.

**Comment by jd0-sag** [comment]
Closing as the approach using AbstractSet is an elegant solution.
