### ISSUE TITLE
Add the ability to reconfigure an active entity

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-apis#44]
Active entities are specified in such a way that they are not allowed to have any state.  This enables entities to transition from passives to actives by replacing passive entity implementations with active ones.  It would be nice to create the ability to reconfigure an active entity API by replacing an active entity with a reconfigured active entity.

**Comment by jd0-sag** [comment]
I don't entirely understand why we need this.  It seems like a lot of little changes will be required for this (make sure we are running this on an exclusive key, persist the updated entity configuration to over-write the existing, handle reconnection of existing clients, and come up with a new set of tests) for something I am not sure is required (unless this somehow makes the coordination reconfigure support easier, but I thought that they worked a little differently).
