### ISSUE TITLE
Move all byte[] transforms to there MessageCodec

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-apis#45]
MessageCodec should be the sole place that byte[] are transformed to objects and back to byte[] for an entity implementation.  This seems cleaner for the entity implementor and more consistent with the overall architecture of the system.  This will also help with more consistent exception handling.

**Comment by jd0-sag** [comment]
This may be resolved by #60 merging.

**Comment by jd0-sag** [comment]
There are a few remaining classes which may want to be changed, under this item:

* `EndpointDelegate` (`handleMessage()` and `createExtendedReconnectData()`)
* `ActiveServerEntity` (`handleReconnect()`)

**Comment by jd0-sag** [comment]
The `handleMessage()` change is somewhat complicated in that it has some interaction with a recent change to ClientCommunicator but it still seems like the right idea.

The changes related to reconnect raise some design questions.  Moving these calls into `MessageCodec` requires that we determine what to use as the message type, here.  Arguably, it makes sense to create a new opaque message type (similar to `EntityMessage` and `EntityResponse`) but that will require adding yet another generic to much of the stack, a change which may seem unwieldy.

**Comment by jd0-sag** [comment]
Note that I will address the `handleMessage()` type under this item.  Once we decide how/if we want to change the methods related to reconnect, we can open a new item for those.
