### ISSUE TITLE
EntityClientService and ServerEntityService should be named consistently

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/terracotta-apis#57]
These classes are the analogues of each other, existing on the client and server, respectively.

Their names are slightly different, as they evolved to these points differently, which makes them hard to search for.

We should change `ServerEntityService` to `EntityServerService` so that they both have the same shape and one is more obvious to find, starting from the other.

**Comment by myronkscott** [comment]
Do this after the creation of a versioning scheme.

**Comment by jd0-sag** [comment]
@ljacomet, @chrisdennis:  Do you guys agree that this is worth doing or should we just close it and not worry about it?  We are at a relatively painless point to change it but more code will start to depend on this, over time.

**Comment by ljacomet** [comment]
I like consistency in APIs and that includes names - so yes from me.

**Comment by ramsai1729** [comment]
ServerEntityService will be renamed to EntityServerService

**Comment by jd0-sag** [comment]
We can probably batch this change together in a release with some of the exception changes we were discussing.  Both are fairly light-weight.
