### ISSUE TITLE
Server-side entities may need a more robust system of communication

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-apis#70]
Currently Active and Passive entities have no means of communicating and coordinating with each other.  This may be needed however extensive discussion needs to be had to understand the bounds.

**Comment by myronkscott** [comment]
There are no requirements for this.  Table this for now until there is a concrete requirement to work against.

**Comment by jd0-sag** [comment]
Has this been rendered moot in light of IEntityMessenger?

**Comment by myronkscott** [comment]
Already implemented
