### ISSUE TITLE
PassthroughServerProcess does not expose client's PID

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#75]
`PlatformConnectedClient` returns -1 with the passthrough system.

**Comment by jd0-sag** [comment]
Ah, I figured this would be an issue, when I saw the change go in.

We need to solve this issue the same way as the client-assigned ports, I suspect.

**Comment by mathieucarbou** [comment]
Oh! I was just working on a PR while you were commenting... ;-)
