### ISSUE TITLE
Create a versioning and release scheme for tc-apis

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-apis#81]
terracotta-apis will evolve over time.  There are enough dependencies now on these apis that any change can cause breakage across many projects.  There is a need for a low impact versioning scheme that will allow API changes without breaking downstream projects on merge.

**Comment by jd0-sag** [comment]
I will take this over since I have been the one keeping tabs on what is happening with the creation of those releaser jobs.

**Comment by jd0-sag** [comment]
Closing this since we now have versioned our core components and have some plans for reducing the cost of this in the future.

Any future work to reduce the instability of the APIs version will start with #121.
